In [1]:
import torch

In [14]:
# x = torch.randn((128, 3, 2))
x = torch.full((128, 3, 1), 1)
x.shape

torch.Size([128, 3, 1])

In [17]:
def get_labels(data):
    # Ensure the input is a 1D tensor
    if data.dim() == 2 and data.size(1) == 1:
        data = data.squeeze()  # Convert from (N, 1) to (N,)

    # Define normalization parameters
    min_val = 15.0
    max_val = 100.0

    # Normalize data to the range [0, 100]
    normalized_data = (data - min_val) / (max_val - min_val) * 100

    # Define thresholds for labeling
    low_risk_threshold = 60
    moderate_risk_threshold = 85
    high_risk_threshold = 100.0

    # Initialize labels tensor
    labels = torch.zeros_like(normalized_data, dtype=torch.long)

    # Apply thresholds for labeling
    labels[normalized_data < low_risk_threshold] = 0    # Low risk
    labels[(normalized_data >= low_risk_threshold) & (normalized_data < moderate_risk_threshold)] = 1  # Moderate risk
    labels[normalized_data >= moderate_risk_threshold] = 2  # High risk

    return  labels.unsqueeze(1).type(torch.float32) 

In [18]:
# Example input tensor
input_tensor = torch.tensor([[0.4803],
                              [0.4883],
                              [0.4726],
                              [0.4657],
                              [0.4710],
                              [0.4884],
                              [0.4831],
                              [0.4762],
                              [0.4671],
                              [0.4692],
                              [0.4713],
                              [0.4655],
                              [0.4761],
                              [0.4763],
                              [0.4756],
                              [0.4811],
                              [0.4750],
                              [0.4830],
                              [0.4656],
                              [0.4888],
                              [0.4810]], dtype=torch.float32)

# Get labels for the input tensor
labels = get_labels(input_tensor)

# Print the resulting labels
print("Labels:\n", labels)

Labels:
 tensor([[0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0],
        [0]])


In [19]:
loss = torch.nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
print(input)
target = torch.empty(3, dtype=torch.long).random_(5)
print(target)
output = loss(input, target)
print(output)

tensor([[ 0.0513,  2.0825,  0.0101, -1.6209, -0.0532],
        [-0.8538, -0.1364, -0.0049, -1.3204, -0.0113],
        [-1.0004, -0.9465,  1.8522, -1.4136,  0.2383]], requires_grad=True)
tensor([1, 3, 4])
tensor(1.6139, grad_fn=<NllLossBackward0>)


In [14]:
fake_labels = torch.full((128, 100, 3), 3, dtype=torch.long)  # Label as class 2
fake_labels.shape
fake_labels.mean(dim=1)

TypeError: full() received an invalid combination of arguments - got (int, int, dtype=torch.dtype), but expected one of:
 * (tuple of ints size, Number fill_value, *, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, Number fill_value, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


In [15]:
target = torch.empty(128, dtype=torch.long).random_(5)
target = target.view(-1)
target.shape

torch.Size([128])

In [21]:
batch_size = 128
seq_len = 100
in_dim = 15
device = "cpu"
import torch
from torch.autograd import Variable
import torch.nn.init as init

noise = Variable(init.normal(torch.zeros(batch_size,seq_len,3),mean=0,std=0.1)).to(device)
out_fake_data = noise.mean(dim=1).argmax(dim=1, keepdim=True)
print(out_fake_data)
labels = torch.Tensor([0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 0, 1, 1, 0,
        2, 1, 2, 2, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 1, 2, 2, 1, 1, 0, 1, 1, 2,
        1, 0, 1, 2, 2, 2, 1, 2, 0, 1, 1, 0, 1, 1, 1, 0, 2, 1, 0, 1, 0, 1, 0, 2,
        2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1, 0, 2, 0, 1, 0, 1, 1, 1, 0, 2, 2, 2, 1,
        0, 2, 0, 1, 2, 0, 0, 1, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 0, 2,
        2, 1, 1, 2, 1, 2, 1, 2])

correct_fake =(out_fake_data == labels).sum().item()
print(correct_fake)

tensor([[2],
        [0],
        [1],
        [0],
        [2],
        [2],
        [1],
        [0],
        [1],
        [0],
        [0],
        [2],
        [1],
        [0],
        [0],
        [2],
        [2],
        [0],
        [1],
        [1],
        [0],
        [2],
        [0],
        [1],
        [1],
        [2],
        [0],
        [2],
        [0],
        [0],
        [2],
        [1],
        [2],
        [2],
        [0],
        [1],
        [2],
        [2],
        [1],
        [1],
        [2],
        [0],
        [2],
        [0],
        [1],
        [1],
        [1],
        [1],
        [2],
        [0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1],
        [1],
        [2],
        [0],
        [2],
        [1],
        [0],
        [2],
        [2],
        [1],
        [2],
        [0],
        [2],
        [0],
        [1],
        [0],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_22756\4233379951.py:9: FutureWarning: `nn.init.normal` is now deprecated in favor of `nn.init.normal_`.
  noise = Variable(init.normal(torch.zeros(batch_size,seq_len,3),mean=0,std=0.1)).to(device)
